- hosts: nfs
  roles:
    - role: geerlingguy.nfs
      nfs_rpcbind_state: started
      nfs_rpcbind_enabled: true
      nfs_exports: [
          "/nfs/dynamic 172.26.0.0/16(rw,sync,no_root_squash)",
          "/nfs/manual 172.26.0.0/16(rw,sync,no_root_squash)"
      ]
